### ISSUE TITLE
error reading html content inside rss feed

### ISSUE THREAD

**Issue by pablonunez-dev** [davorg/xml-feed#16]
i´m trying to parse and read the content of a rss feed and getting an error.

xml feed for testing

    <?xml version="1.0" encoding="UTF-8"?>
    <rss version="2.0" xmlns:Test="http://www.Test.com">
    <channel>
        <title>Deportes - Test.com</title>
           <link>http://www.Test.com</link>
               <description>Últimas noticias de deportes</description>
               <item>
                        <title><![CDATA[El 'Chacho' Coudet es el nuevo entrenador de Rosario Central]]></title>
                        <link>http://442.Test.com/2014-12-15-326653-coudet-fue-presentado-como-nuevo-dt-de-central/</link>
                        <description><![CDATA[El&nbsp;Chacho, Tengo mucha alegr&iacute;a y ganas de empezar a trabajar.&nbsp;No esperaba que sea ac&aacute;&rdquo;, reconoci&oacute;.]]></description>
                        <category><![CDATA[Deportes]]></category>
                        <pubDate>15 12 2014 06:15:0 +0000</pubDate>
                        <enclosure url="http://www.Test.com/__export/1418678333348/sites/diarioTest/img/2014/12/15/deportes/1215_coudet_g_fb.jpg" type="image/jpeg"><![CDATA[El Chacho Coudet]]></enclosure>
                        <author><![CDATA[]]></author>
                        <content><![CDATA[<p>Eduardo Coudet&nbsp;fue presentado como nuevo entrenador         deRosario Central&nbsp.</p>
    ]]></content>
            </item>
        </channel>
    </rss>

This is my test.pl script file.

    #!/usr/bin/perl
    use strict;
    use warnings;
    use XML::Feed;
    
    my $feed = XML::Feed->parse("test.xml");
    
    for my $entry ($feed->entries) {
    
       print $entry->content;
    
    }

when i run this code i get this error.

    Can't use string ("<p>Eduardo Coudet&nbsp;fue prese"...) as a HASH ref while "st
    rict refs" in use at C:/Strawberry/perl/site/lib/XML/Feed/Entry/Format/RSS.pm li
    ne 91.

i think is a bug inside XML::Feed

**Comment by davorg** [comment]
Fixed in 0.53.

**Comment by pablonunez-dev** [comment]
Thank you
