### ISSUE TITLE
Date format invalidates atom feeds

### ISSUE THREAD

**Issue by davorg** [davorg/xml-feed#21]
See https://rt.cpan.org/Ticket/Display.html?id=48337 for details

**Comment by goober99** [comment]
The updated() method in XML::Feed::Format::Atom is inherited from XML::Atom::Feed, so the bug is actually in XML::Atom::Feed. I could override the updated() method in XML::Feed::Format::Atom to do the right thing. Or would you rather me send a pull request to XML::Atom fixing the issue upstream?

**Comment by davorg** [comment]
I think fixing it in XML::Atom is the right thing to do. Feel free to send it to either my fork or Miyagawa's upstream version.

**Comment by goober99** [comment]
I spoke too hastily assuming the issue was in XML::Atom. As I dug into XML::Atom, I discovered its updated() method just takes a string. It doesn't do any date formatting like XML::Feed. You could set updated('Foo'), and it would output <updated>Foo</updated>.
