### ISSUE TITLE
Sloppy use of '||'

### ISSUE THREAD

**Issue by davorg** [davorg/xml-feed#24]
See https://rt.cpan.org/Ticket/Display.html?id=69543 for details

**Comment by goober99** [comment]
This sounds like an ideal use case for defined-or (`//`), but I don't know if you want to introduce a dependency on Perl 5.10 or greater (5.10 is almost ten years old now). I don't mind tackling this, but let me know what route you'd like me to take: defined-or or adding a whole bunch of `defined`s.

**Comment by davorg** [comment]
Thanks for looking at these. I'd be very happy to bump the dependency to Perl 5.10.

I have a vague memory of trying to fix some of these many years ago, but I can't find it in the commit log. So don't be too surprised if some of them are already fixed.
