### ISSUE TITLE
Massive memory leak when calling XML::Feed::Entry::Format::RSS->issued()

### ISSUE THREAD

**Issue by bbkr** [davorg/xml-feed#57]
Steps to reproduce:

```
use XML::Feed;

my $feed = XML::Feed->parse(URI->new('https://www.businessinsider.de/feed/gs-wds-nl-stream'));
my $entry = [$feed->entries]->[0];
$entry->issued for 1..1000000000;
```

It leaks memory at a rate of few MB per second on my machine.

XML::Feed version: 0.61
Perl version: 5.32.1

**Comment by bbkr** [comment]
After digging I've found the issue is caused by `DateTime::Format::Flexible` - https://github.com/davorg/xml-feed/blob/572b8de969454d9a8b95e75eb28a282ab8f4c56e/lib/XML/Feed/Util.pm#L35 .

This will leak badly (and is also exceptionally slow).
```
DateTime::Format::Flexible->parse_datetime('Mon, 24 May 2021 05:55:00 +0200') for 1..100000000
```

I think this section should be refactored to use cheap and fast parsing on RFC822 date first, because this format is official RSS 2.0 spec: https://validator.w3.org/feed/docs/rss2.html .

DWIM-ness and pulling heavy and slow parser artillery like `DateTime::Format::Flexible` should be optional.

**Comment by bbkr** [comment]
To summarize:
* There is typo in the code that causes `DateTime::Format::Mail` to never match and fall back to `DateTime::Format::Flexible`.
* `DateTime::Format::Flexible` has massive memory leaks.

While typo is easy to fix the question is what do to with memory leak in `DateTime::Format::Flexible`? Do we need this level of DWIM-ness if RSS 2.0 spec explicitly tells that dates should have RFC822 format? Should `<pubDate>1-1</pubDate>` really be parsed? I think non-strict parsing provided by this module should at least be switchable.

**Comment by davorg** [comment]
Hi,

Thanks for the report. I'll fix the typo so and that will fix your immediate problem (assuming your feeds have timestamps in a valid format). I think you're right that the more flexible timestamp parsing should be an optional feature and I'll raise a ticket to remind myself to fix that in the future.

I think it's also worth you raising a ticket against DateTime::Format::Flexible, telling the author about the memory leak.

**Comment by davorg** [comment]
Version 0.62 en route to CPAN now.

**Comment by bbkr** [comment]
Awesome. I've made report in `DateTime::Format::Flexible`.
https://rt.cpan.org/Ticket/Display.html?id=136597
