### ISSUE TITLE
URI::Fetch dependency has critical unresolved bug

### ISSUE THREAD

**Issue by bbkr** [davorg/xml-feed#59]
Currently module cannot be installed on latest clean Perl because `URI::Fetch` fails to pass Configure phase:  https://rt.cpan.org/Public/Bug/Display.html?id=133491

Looks like this is only used as simple wrapper for checking 410 status:
https://github.com/davorg/xml-feed/blob/572b8de969454d9a8b95e75eb28a282ab8f4c56e/lib/XML/Feed.pm#L99

Is there any specific reason to have both LWP::UserAgent and URI::Fetch in dependencies?
With all respect to `URI::Fetch` author - last release was 5 years ago, critical bug is not resolved for a week and module does not have any modern CI setup that will warn about such situations. Which leads to conclusions that this module is stalled.

**Comment by davorg** [comment]
URI::Fetch is definitely a better option for fetching web feeds (which is, after all, what we're doing here).

It looks like Neil is aware of the problem. He made a commit yesterday that fixes this problems - https://github.com/neilb/URI-Fetch/commit/8a7189fcd38875f86e57a0396c1b904dd475daa9

I'm going to wait a couple of days to see if he releases it. If he doesn't then I'll reconsider and maybe switch to using HTTP::Tiny instead.

**Comment by bbkr** [comment]
New URI::Fetch release just happened, it works on clean Perl and does not block installation of XML::Feed.

Issue can now be closed. Thank you for your time!

**Comment by davorg** [comment]
That's great. It also means that my CI has passed for the first time since I set it up :-)

https://github.com/davorg/xml-feed/actions
